<h2>Support and release notes</h2>

<ul>
<li>To receive notifications about new releases, please subscribe to our mailing list by following <a href="https://lists.desy.de/sympa/subscribe/chimeratk-announcements">this link</a>.</li>
<li>To contact the developers for support, please write to this mail address: <a href="mailto:chimeratk-support@desy.de">chimeratk-support@desy.de</a></li>
<ul>

</body>
</html>
