var annotated_dup =
[
    [ "open62541_MacroHelper", "namespaceopen62541___macro_helper.html", [
      [ "open62541_MacroHelper", "classopen62541___macro_helper_1_1open62541___macro_helper.html", "classopen62541___macro_helper_1_1open62541___macro_helper" ]
    ] ],
    [ "open62541_XMLPreprocessor", "namespaceopen62541___x_m_l_preprocessor.html", [
      [ "preProcessDocument", "classopen62541___x_m_l_preprocessor_1_1pre_process_document.html", "classopen62541___x_m_l_preprocessor_1_1pre_process_document" ],
      [ "open62541_XMLPreprocessor", "classopen62541___x_m_l_preprocessor_1_1open62541___x_m_l_preprocessor.html", "classopen62541___x_m_l_preprocessor_1_1open62541___x_m_l_preprocessor" ]
    ] ],
    [ "ua_builtin_types", "namespaceua__builtin__types.html", [
      [ "opcua_value_t", "classua__builtin__types_1_1opcua__value__t.html", "classua__builtin__types_1_1opcua__value__t" ],
      [ "opcua_BuiltinType_extensionObject_t", "classua__builtin__types_1_1opcua___builtin_type__extension_object__t.html", "classua__builtin__types_1_1opcua___builtin_type__extension_object__t" ],
      [ "opcua_BuiltinType_localizedtext_t", "classua__builtin__types_1_1opcua___builtin_type__localizedtext__t.html", "classua__builtin__types_1_1opcua___builtin_type__localizedtext__t" ],
      [ "opcua_BuiltinType_expandednodeid_t", "classua__builtin__types_1_1opcua___builtin_type__expandednodeid__t.html", "classua__builtin__types_1_1opcua___builtin_type__expandednodeid__t" ],
      [ "opcua_BuiltinType_nodeid_t", "classua__builtin__types_1_1opcua___builtin_type__nodeid__t.html", "classua__builtin__types_1_1opcua___builtin_type__nodeid__t" ],
      [ "opcua_BuiltinType_datetime_t", "classua__builtin__types_1_1opcua___builtin_type__datetime__t.html", "classua__builtin__types_1_1opcua___builtin_type__datetime__t" ],
      [ "opcua_BuiltinType_qualifiedname_t", "classua__builtin__types_1_1opcua___builtin_type__qualifiedname__t.html", "classua__builtin__types_1_1opcua___builtin_type__qualifiedname__t" ],
      [ "opcua_BuiltinType_statuscode_t", "classua__builtin__types_1_1opcua___builtin_type__statuscode__t.html", "classua__builtin__types_1_1opcua___builtin_type__statuscode__t" ],
      [ "opcua_BuiltinType_diagnosticinfo_t", "classua__builtin__types_1_1opcua___builtin_type__diagnosticinfo__t.html", "classua__builtin__types_1_1opcua___builtin_type__diagnosticinfo__t" ],
      [ "opcua_BuiltinType_guid_t", "classua__builtin__types_1_1opcua___builtin_type__guid__t.html", "classua__builtin__types_1_1opcua___builtin_type__guid__t" ],
      [ "opcua_BuiltinType_boolean_t", "classua__builtin__types_1_1opcua___builtin_type__boolean__t.html", "classua__builtin__types_1_1opcua___builtin_type__boolean__t" ],
      [ "opcua_BuiltinType_byte_t", "classua__builtin__types_1_1opcua___builtin_type__byte__t.html", "classua__builtin__types_1_1opcua___builtin_type__byte__t" ],
      [ "opcua_BuiltinType_sbyte_t", "classua__builtin__types_1_1opcua___builtin_type__sbyte__t.html", "classua__builtin__types_1_1opcua___builtin_type__sbyte__t" ],
      [ "opcua_BuiltinType_int16_t", "classua__builtin__types_1_1opcua___builtin_type__int16__t.html", "classua__builtin__types_1_1opcua___builtin_type__int16__t" ],
      [ "opcua_BuiltinType_uint16_t", "classua__builtin__types_1_1opcua___builtin_type__uint16__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint16__t" ],
      [ "opcua_BuiltinType_int32_t", "classua__builtin__types_1_1opcua___builtin_type__int32__t.html", "classua__builtin__types_1_1opcua___builtin_type__int32__t" ],
      [ "opcua_BuiltinType_uint32_t", "classua__builtin__types_1_1opcua___builtin_type__uint32__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint32__t" ],
      [ "opcua_BuiltinType_int64_t", "classua__builtin__types_1_1opcua___builtin_type__int64__t.html", "classua__builtin__types_1_1opcua___builtin_type__int64__t" ],
      [ "opcua_BuiltinType_uint64_t", "classua__builtin__types_1_1opcua___builtin_type__uint64__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint64__t" ],
      [ "opcua_BuiltinType_float_t", "classua__builtin__types_1_1opcua___builtin_type__float__t.html", "classua__builtin__types_1_1opcua___builtin_type__float__t" ],
      [ "opcua_BuiltinType_double_t", "classua__builtin__types_1_1opcua___builtin_type__double__t.html", "classua__builtin__types_1_1opcua___builtin_type__double__t" ],
      [ "opcua_BuiltinType_string_t", "classua__builtin__types_1_1opcua___builtin_type__string__t.html", "classua__builtin__types_1_1opcua___builtin_type__string__t" ],
      [ "opcua_BuiltinType_xmlelement_t", "classua__builtin__types_1_1opcua___builtin_type__xmlelement__t.html", "classua__builtin__types_1_1opcua___builtin_type__xmlelement__t" ],
      [ "opcua_BuiltinType_bytestring_t", "classua__builtin__types_1_1opcua___builtin_type__bytestring__t.html", "classua__builtin__types_1_1opcua___builtin_type__bytestring__t" ]
    ] ],
    [ "ua_namespace", "namespaceua__namespace.html", [
      [ "opcua_namespace", "classua__namespace_1_1opcua__namespace.html", "classua__namespace_1_1opcua__namespace" ],
      [ "testing", "classua__namespace_1_1testing.html", "classua__namespace_1_1testing" ],
      [ "testing_open62541_header", "classua__namespace_1_1testing__open62541__header.html", "classua__namespace_1_1testing__open62541__header" ]
    ] ],
    [ "ua_node_types", "namespaceua__node__types.html", [
      [ "opcua_referencePointer_t", "classua__node__types_1_1opcua__reference_pointer__t.html", "classua__node__types_1_1opcua__reference_pointer__t" ],
      [ "opcua_node_id_t", "classua__node__types_1_1opcua__node__id__t.html", "classua__node__types_1_1opcua__node__id__t" ],
      [ "opcua_node_t", "classua__node__types_1_1opcua__node__t.html", "classua__node__types_1_1opcua__node__t" ],
      [ "opcua_node_referenceType_t", "classua__node__types_1_1opcua__node__reference_type__t.html", "classua__node__types_1_1opcua__node__reference_type__t" ],
      [ "opcua_node_object_t", "classua__node__types_1_1opcua__node__object__t.html", "classua__node__types_1_1opcua__node__object__t" ],
      [ "opcua_node_variable_t", "classua__node__types_1_1opcua__node__variable__t.html", "classua__node__types_1_1opcua__node__variable__t" ],
      [ "opcua_node_method_t", "classua__node__types_1_1opcua__node__method__t.html", "classua__node__types_1_1opcua__node__method__t" ],
      [ "opcua_node_objectType_t", "classua__node__types_1_1opcua__node__object_type__t.html", "classua__node__types_1_1opcua__node__object_type__t" ],
      [ "opcua_node_variableType_t", "classua__node__types_1_1opcua__node__variable_type__t.html", "classua__node__types_1_1opcua__node__variable_type__t" ],
      [ "opcua_node_dataType_t", "classua__node__types_1_1opcua__node__data_type__t.html", "classua__node__types_1_1opcua__node__data_type__t" ],
      [ "opcua_node_view_t", "classua__node__types_1_1opcua__node__view__t.html", "classua__node__types_1_1opcua__node__view__t" ]
    ] ],
    [ "AdditionalVariableTest", "class_additional_variable_test.html", null ],
    [ "AdditionalVariableTestSuite", "class_additional_variable_test_suite.html", "class_additional_variable_test_suite" ],
    [ "csa_opcua_adapter", "classcsa__opcua__adapter.html", "classcsa__opcua__adapter" ],
    [ "CSAOPCUATest", "class_c_s_a_o_p_c_u_a_test.html", null ],
    [ "CSAOPCUATestSuite", "class_c_s_a_o_p_c_u_a_test_suite.html", "class_c_s_a_o_p_c_u_a_test_suite" ],
    [ "FolderInfo", "struct_folder_info.html", "struct_folder_info" ],
    [ "MyApp", "struct_my_app.html", "struct_my_app" ],
    [ "ProcessVariableTest", "class_process_variable_test.html", null ],
    [ "ProcessVariableTestSuite", "class_process_variable_test_suite.html", "class_process_variable_test_suite" ],
    [ "runtime_value_generator", "classruntime__value__generator.html", "classruntime__value__generator" ],
    [ "ServerConfig", "struct_server_config.html", "struct_server_config" ],
    [ "TestFixtureEmptySet", "struct_test_fixture_empty_set.html", "struct_test_fixture_empty_set" ],
    [ "TestFixturePVSet", "struct_test_fixture_p_v_set.html", "struct_test_fixture_p_v_set" ],
    [ "TestFixtureServerSet", "struct_test_fixture_server_set.html", "struct_test_fixture_server_set" ],
    [ "ua_additionalvariable", "classua__additionalvariable.html", "classua__additionalvariable" ],
    [ "UA_DataSource_Map_Element_t", "struct_u_a___data_source___map___element__t.html", "struct_u_a___data_source___map___element__t" ],
    [ "ua_mapped_class", "classua__mapped__class.html", "classua__mapped__class" ],
    [ "UA_NodeId_pair_t", "struct_u_a___node_id__pair__t.html", "struct_u_a___node_id__pair__t" ],
    [ "ua_processvariable", "classua__processvariable.html", "classua__processvariable" ],
    [ "ua_proxies", "classua__proxies.html", null ],
    [ "ua_uaadapter", "classua__uaadapter.html", "classua__uaadapter" ],
    [ "UAAdapterTest", "class_u_a_adapter_test.html", null ],
    [ "UAAdapterTestSuite", "class_u_a_adapter_test_suite.html", "class_u_a_adapter_test_suite" ],
    [ "UAMappingTest", "class_u_a_mapping_test.html", null ],
    [ "UAMappingTestSuite", "class_u_a_mapping_test_suite.html", "class_u_a_mapping_test_suite" ],
    [ "xml_file_handler", "classxml__file__handler.html", "classxml__file__handler" ],
    [ "XMLFileHandlerTest", "class_x_m_l_file_handler_test.html", null ],
    [ "XMLFileHandlerTestSuite", "class_x_m_l_file_handler_test_suite.html", "class_x_m_l_file_handler_test_suite" ]
];