var namespaceua__builtin__types =
[
    [ "opcua_BuiltinType_boolean_t", "classua__builtin__types_1_1opcua___builtin_type__boolean__t.html", "classua__builtin__types_1_1opcua___builtin_type__boolean__t" ],
    [ "opcua_BuiltinType_byte_t", "classua__builtin__types_1_1opcua___builtin_type__byte__t.html", "classua__builtin__types_1_1opcua___builtin_type__byte__t" ],
    [ "opcua_BuiltinType_bytestring_t", "classua__builtin__types_1_1opcua___builtin_type__bytestring__t.html", "classua__builtin__types_1_1opcua___builtin_type__bytestring__t" ],
    [ "opcua_BuiltinType_datetime_t", "classua__builtin__types_1_1opcua___builtin_type__datetime__t.html", "classua__builtin__types_1_1opcua___builtin_type__datetime__t" ],
    [ "opcua_BuiltinType_diagnosticinfo_t", "classua__builtin__types_1_1opcua___builtin_type__diagnosticinfo__t.html", "classua__builtin__types_1_1opcua___builtin_type__diagnosticinfo__t" ],
    [ "opcua_BuiltinType_double_t", "classua__builtin__types_1_1opcua___builtin_type__double__t.html", "classua__builtin__types_1_1opcua___builtin_type__double__t" ],
    [ "opcua_BuiltinType_expandednodeid_t", "classua__builtin__types_1_1opcua___builtin_type__expandednodeid__t.html", "classua__builtin__types_1_1opcua___builtin_type__expandednodeid__t" ],
    [ "opcua_BuiltinType_extensionObject_t", "classua__builtin__types_1_1opcua___builtin_type__extension_object__t.html", "classua__builtin__types_1_1opcua___builtin_type__extension_object__t" ],
    [ "opcua_BuiltinType_float_t", "classua__builtin__types_1_1opcua___builtin_type__float__t.html", "classua__builtin__types_1_1opcua___builtin_type__float__t" ],
    [ "opcua_BuiltinType_guid_t", "classua__builtin__types_1_1opcua___builtin_type__guid__t.html", "classua__builtin__types_1_1opcua___builtin_type__guid__t" ],
    [ "opcua_BuiltinType_int16_t", "classua__builtin__types_1_1opcua___builtin_type__int16__t.html", "classua__builtin__types_1_1opcua___builtin_type__int16__t" ],
    [ "opcua_BuiltinType_int32_t", "classua__builtin__types_1_1opcua___builtin_type__int32__t.html", "classua__builtin__types_1_1opcua___builtin_type__int32__t" ],
    [ "opcua_BuiltinType_int64_t", "classua__builtin__types_1_1opcua___builtin_type__int64__t.html", "classua__builtin__types_1_1opcua___builtin_type__int64__t" ],
    [ "opcua_BuiltinType_localizedtext_t", "classua__builtin__types_1_1opcua___builtin_type__localizedtext__t.html", "classua__builtin__types_1_1opcua___builtin_type__localizedtext__t" ],
    [ "opcua_BuiltinType_nodeid_t", "classua__builtin__types_1_1opcua___builtin_type__nodeid__t.html", "classua__builtin__types_1_1opcua___builtin_type__nodeid__t" ],
    [ "opcua_BuiltinType_qualifiedname_t", "classua__builtin__types_1_1opcua___builtin_type__qualifiedname__t.html", "classua__builtin__types_1_1opcua___builtin_type__qualifiedname__t" ],
    [ "opcua_BuiltinType_sbyte_t", "classua__builtin__types_1_1opcua___builtin_type__sbyte__t.html", "classua__builtin__types_1_1opcua___builtin_type__sbyte__t" ],
    [ "opcua_BuiltinType_statuscode_t", "classua__builtin__types_1_1opcua___builtin_type__statuscode__t.html", "classua__builtin__types_1_1opcua___builtin_type__statuscode__t" ],
    [ "opcua_BuiltinType_string_t", "classua__builtin__types_1_1opcua___builtin_type__string__t.html", "classua__builtin__types_1_1opcua___builtin_type__string__t" ],
    [ "opcua_BuiltinType_uint16_t", "classua__builtin__types_1_1opcua___builtin_type__uint16__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint16__t" ],
    [ "opcua_BuiltinType_uint32_t", "classua__builtin__types_1_1opcua___builtin_type__uint32__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint32__t" ],
    [ "opcua_BuiltinType_uint64_t", "classua__builtin__types_1_1opcua___builtin_type__uint64__t.html", "classua__builtin__types_1_1opcua___builtin_type__uint64__t" ],
    [ "opcua_BuiltinType_xmlelement_t", "classua__builtin__types_1_1opcua___builtin_type__xmlelement__t.html", "classua__builtin__types_1_1opcua___builtin_type__xmlelement__t" ],
    [ "opcua_value_t", "classua__builtin__types_1_1opcua__value__t.html", "classua__builtin__types_1_1opcua__value__t" ]
];