var annotated_dup =
[
    [ "ChimeraTK", "namespace_chimera_t_k.html", [
      [ "DoocsProcessArray", "class_chimera_t_k_1_1_doocs_process_array.html", "class_chimera_t_k_1_1_doocs_process_array" ],
      [ "CSAdapterEqFct", "class_chimera_t_k_1_1_c_s_adapter_eq_fct.html", "class_chimera_t_k_1_1_c_s_adapter_eq_fct" ],
      [ "DoocsAdapter", "class_chimera_t_k_1_1_doocs_adapter.html", "class_chimera_t_k_1_1_doocs_adapter" ],
      [ "DoocsIfff", "class_chimera_t_k_1_1_doocs_ifff.html", "class_chimera_t_k_1_1_doocs_ifff" ],
      [ "MappedDoocsImg", "struct_chimera_t_k_1_1_mapped_doocs_img.html", "struct_chimera_t_k_1_1_mapped_doocs_img" ],
      [ "DoocsImage", "class_chimera_t_k_1_1_doocs_image.html", "class_chimera_t_k_1_1_doocs_image" ],
      [ "DoocsProcessScalar", "class_chimera_t_k_1_1_doocs_process_scalar.html", "class_chimera_t_k_1_1_doocs_process_scalar" ],
      [ "DoocsPVFactory", "class_chimera_t_k_1_1_doocs_p_v_factory.html", "class_chimera_t_k_1_1_doocs_p_v_factory" ],
      [ "DoocsSpectrum", "class_chimera_t_k_1_1_doocs_spectrum.html", "class_chimera_t_k_1_1_doocs_spectrum" ],
      [ "DoocsUpdater", "class_chimera_t_k_1_1_doocs_updater.html", "class_chimera_t_k_1_1_doocs_updater" ],
      [ "DoocsXy", "class_chimera_t_k_1_1_doocs_xy.html", "class_chimera_t_k_1_1_doocs_xy" ],
      [ "PropertyBase", "class_chimera_t_k_1_1_property_base.html", "class_chimera_t_k_1_1_property_base" ],
      [ "PersistConfig", "struct_chimera_t_k_1_1_persist_config.html", "struct_chimera_t_k_1_1_persist_config" ],
      [ "PropertyAttributes", "struct_chimera_t_k_1_1_property_attributes.html", "struct_chimera_t_k_1_1_property_attributes" ],
      [ "PropertyDescription", "struct_chimera_t_k_1_1_property_description.html", "struct_chimera_t_k_1_1_property_description" ],
      [ "AutoPropertyDescription", "struct_chimera_t_k_1_1_auto_property_description.html", "struct_chimera_t_k_1_1_auto_property_description" ],
      [ "ImageDescription", "struct_chimera_t_k_1_1_image_description.html", "struct_chimera_t_k_1_1_image_description" ],
      [ "SpectrumDescription", "struct_chimera_t_k_1_1_spectrum_description.html", "struct_chimera_t_k_1_1_spectrum_description" ],
      [ "XyDescription", "struct_chimera_t_k_1_1_xy_description.html", "struct_chimera_t_k_1_1_xy_description" ],
      [ "IfffDescription", "struct_chimera_t_k_1_1_ifff_description.html", "struct_chimera_t_k_1_1_ifff_description" ],
      [ "LocationInfo", "struct_chimera_t_k_1_1_location_info.html", "struct_chimera_t_k_1_1_location_info" ],
      [ "ErrorReportingInfo", "struct_chimera_t_k_1_1_error_reporting_info.html", "struct_chimera_t_k_1_1_error_reporting_info" ],
      [ "StatusHandler", "class_chimera_t_k_1_1_status_handler.html", "class_chimera_t_k_1_1_status_handler" ],
      [ "VariableMapper", "class_chimera_t_k_1_1_variable_mapper.html", "class_chimera_t_k_1_1_variable_mapper" ]
    ] ],
    [ "BusinessLogic", "struct_business_logic.html", "struct_business_logic" ],
    [ "D_textUnifier", "struct_d__text_unifier.html", "struct_d__text_unifier" ],
    [ "DeviceFixture", "struct_device_fixture.html", "struct_device_fixture" ],
    [ "GlobalFixture", "struct_global_fixture.html", "struct_global_fixture" ],
    [ "TestableCSAdapterEqFct", "class_testable_c_s_adapter_eq_fct.html", "class_testable_c_s_adapter_eq_fct" ],
    [ "TestableDoocsSpectrum", "class_testable_doocs_spectrum.html", "class_testable_doocs_spectrum" ],
    [ "ZmqData", "struct_zmq_data.html", "struct_zmq_data" ],
    [ "ZMQFixture", "struct_z_m_q_fixture.html", "struct_z_m_q_fixture" ]
];