var hierarchy =
[
    [ "cppext::barrier", "classcppext_1_1barrier.html", null ],
    [ "cppext::detail::continuation_process_async< T, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__async.html", null ],
    [ "cppext::detail::continuation_process_async< T, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__async_3_01_t_00_01_f_e_a_t_u_r_e_s_00_01void_00_01_c_a_l_l_a_b_l_e_01_4.html", null ],
    [ "cppext::detail::continuation_process_async< void, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__async_3_01void_00_01_f_e_a_t_u_r_e_s_00_01_t_o_u_t_00_01_c_a_l_l_a_b_l_e_01_4.html", null ],
    [ "cppext::detail::continuation_process_async< void, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__async_3_01void_00_01_f_e_a_t_u_r_e_s_00_01void_00_01_c_a_l_l_a_b_l_e_01_4.html", null ],
    [ "cppext::detail::continuation_process_deferred< T, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred.html", null ],
    [ "cppext::detail::continuation_process_deferred< T, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred_3_01_t_00_01_f_e_a_t_u_r_e_s_00_01void_00_01_c_a_l_l_a_b_l_e_01_4.html", null ],
    [ "cppext::detail::continuation_process_deferred< void, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred_3_01void_00_01_f_e_a_t_u_r_e_s_00_01_tebac6b82d650ef2e626607dc64772a3f.html", null ],
    [ "cppext::detail::continuation_process_deferred< void, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred_3_01void_00_01_f_e_a_t_u_r_e_s_00_01void_00_01_c_a_l_l_a_b_l_e_01_4.html", null ],
    [ "cppext::detail::continuation_process_deferred_wait< T, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred__wait.html", null ],
    [ "cppext::detail::continuation_process_deferred_wait< T, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred__wait_3_01_t_00_01_f_e_a_t_u_r_e_s_00_f125d47f1dc6f55ac0f64a59f19dd10b.html", null ],
    [ "cppext::detail::continuation_process_deferred_wait< void, FEATURES, TOUT, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred__wait_3_01void_00_01_f_e_a_t_u_r_e_s_04ff549cc3a9749cd545516f02066a65d.html", null ],
    [ "cppext::detail::continuation_process_deferred_wait< void, FEATURES, void, CALLABLE >", "structcppext_1_1detail_1_1continuation__process__deferred__wait_3_01void_00_01_f_e_a_t_u_r_e_s_0df633098c19dd87ca4327b9fab9539ac.html", null ],
    [ "cppext::final_act< F >", "classcppext_1_1final__act.html", null ],
    [ "cppext::future_queue< T, FEATURES >", "classcppext_1_1future__queue.html", null ],
    [ "cppext::future_queue< TOUT >", "classcppext_1_1future__queue.html", null ],
    [ "cppext::future_queue< void >", "classcppext_1_1future__queue.html", null ],
    [ "cppext::future_queue< void, FEATURES >", "classcppext_1_1future__queue.html", null ],
    [ "cppext::future_queue_base", "classcppext_1_1future__queue__base.html", null ],
    [ "helper_iterator", "classhelper__iterator.html", null ],
    [ "std::iterator_traits< helper_iterator >", "structstd_1_1iterator__traits_3_01helper__iterator_01_4.html", null ],
    [ "MovableDataType", "struct_movable_data_type.html", null ],
    [ "cppext::MOVE_DATA", "classcppext_1_1_m_o_v_e___d_a_t_a.html", null ],
    [ "MyException", "class_my_exception.html", null ],
    [ "cppext::semaphore", "classcppext_1_1semaphore.html", null ],
    [ "cppext::detail::shared_state< T >", "structcppext_1_1detail_1_1shared__state.html", null ],
    [ "cppext::detail::shared_state_base", "structcppext_1_1detail_1_1shared__state__base.html", [
      [ "cppext::detail::shared_state< void >", "structcppext_1_1detail_1_1shared__state_3_01void_01_4.html", null ]
    ] ],
    [ "cppext::detail::shared_state_ptr", "structcppext_1_1detail_1_1shared__state__ptr.html", null ],
    [ "cppext::SWAP_DATA", "classcppext_1_1_s_w_a_p___d_a_t_a.html", null ],
    [ "cppext::detail::TerminateInternalThread", "classcppext_1_1detail_1_1_terminate_internal_thread.html", null ],
    [ "cppext::experimental::type_erasing_vector< CALLABLE >", "classcppext_1_1experimental_1_1type__erasing__vector.html", null ],
    [ "cppext::detail::when_any_notification_info", "structcppext_1_1detail_1_1when__any__notification__info.html", null ]
];