var dir_171063ca2b6d8df6d9147a9ad3041fe6 =
[
    [ "serverTestAutoCreateLocations.cpp", "server_test_auto_create_locations_8cpp.html", "server_test_auto_create_locations_8cpp" ],
    [ "serverTestCallOptimiseUnmappedVariables.cpp", "server_test_call_optimise_unmapped_variables_8cpp.html", "server_test_call_optimise_unmapped_variables_8cpp" ],
    [ "serverTestDataMatching.cpp", "server_test_data_matching_8cpp.html", "server_test_data_matching_8cpp" ],
    [ "serverTestErrorFlag.cpp", "server_test_error_flag_8cpp.html", "server_test_error_flag_8cpp" ],
    [ "serverTestGlobalTurnOnOffHistory.cpp", "server_test_global_turn_on_off_history_8cpp.html", "server_test_global_turn_on_off_history_8cpp" ],
    [ "serverTestGlobalTurnOnOffWriteable.cpp", "server_test_global_turn_on_off_writeable_8cpp.html", "server_test_global_turn_on_off_writeable_8cpp" ],
    [ "serverTestIfff.cpp", "server_test_ifff_8cpp.html", "server_test_ifff_8cpp" ],
    [ "serverTestImportAllIntoLocation.cpp", "server_test_import_all_into_location_8cpp.html", "server_test_import_all_into_location_8cpp" ],
    [ "serverTestPlainVariableCreation.cpp", "server_test_plain_variable_creation_8cpp.html", "server_test_plain_variable_creation_8cpp" ],
    [ "serverTestReadWrite.cpp", "server_test_read_write_8cpp.html", "server_test_read_write_8cpp" ],
    [ "serverTestRenameImport.cpp", "server_test_rename_import_8cpp.html", "server_test_rename_import_8cpp" ],
    [ "serverTestRetypeProperties.cpp", "server_test_retype_properties_8cpp.html", "server_test_retype_properties_8cpp" ],
    [ "serverTestSpectrumArray.cpp", "server_test_spectrum_array_8cpp.html", "server_test_spectrum_array_8cpp" ],
    [ "serverTestSpectrumBuffer-exception.cpp", "server_test_spectrum_buffer-exception_8cpp.html", "server_test_spectrum_buffer-exception_8cpp" ],
    [ "serverTestSpectrumBuffer.cpp", "server_test_spectrum_buffer_8cpp.html", "server_test_spectrum_buffer_8cpp" ],
    [ "serverTestVariableMapperWithLocationAndCode.cpp", "server_test_variable_mapper_with_location_and_code_8cpp.html", "server_test_variable_mapper_with_location_and_code_8cpp" ],
    [ "serverTestXy.cpp", "server_test_xy_8cpp.html", "server_test_xy_8cpp" ],
    [ "serverTestZeroMQ.cpp", "server_test_zero_m_q_8cpp.html", "server_test_zero_m_q_8cpp" ],
    [ "serverTestZMQ_CsToApp.cpp", "server_test_z_m_q___cs_to_app_8cpp.html", "server_test_z_m_q___cs_to_app_8cpp" ],
    [ "testBasenameFromAddress.cpp", "test_basename_from_address_8cpp.html", "test_basename_from_address_8cpp" ],
    [ "testCSAdapterEqFct.cpp", "test_c_s_adapter_eq_fct_8cpp.html", "test_c_s_adapter_eq_fct_8cpp" ],
    [ "testDoocsAdapter.cpp", "test_doocs_adapter_8cpp.html", "test_doocs_adapter_8cpp" ],
    [ "testDoocsProcessScalar.cpp", "test_doocs_process_scalar_8cpp.html", "test_doocs_process_scalar_8cpp" ],
    [ "testDoocsPVFactory.cpp", "test_doocs_p_v_factory_8cpp.html", "test_doocs_p_v_factory_8cpp" ],
    [ "testDoocsSpectrum.cpp", "test_doocs_spectrum_8cpp.html", "test_doocs_spectrum_8cpp" ],
    [ "testSplitStringAtFirstSlash.cpp", "test_split_string_at_first_slash_8cpp.html", "test_split_string_at_first_slash_8cpp" ],
    [ "testVariableMapper.cpp", "test_variable_mapper_8cpp.html", "test_variable_mapper_8cpp" ]
];